spring:
  datasource:
    url: jdbc:mysql://mysql:3306/supply
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
server:
  port: 9093