version: "3"

services:

  scheduler:
    image: ghcr.io/worldfam/scheduler:latest
    ports:
      - "9090:9090"

  supply:
    image: ghcr.io/worldfam/supply:latest
    ports:
      - "9093:9093"
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: supply
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:mysql://mysql:3306/supply -user=root -password=password -connectRetries=60 migrate
    depends_on:
      - mysql
    volumes:
      - ./flyway-scripts:/flyway/sql