version: "3"

services:

  scheduler:
    image: ghcr.io/worldfam/scheduler:latest
    ports:
      - "9090:9090"

  supply:
    image: ghcr.io/worldfam/supply:latest
    ports:
      - "9093:9093"
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: supply_management
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: