version: "3"

services:

#### Services ####

  order-ui:
    container_name: order-ui
    build:
      context: ./order-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  logging:
    container_name: logging
    build:
      context: ./logging
      dockerfile: Dockerfile
    ports:
      - "8765:8765"

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - mongo

  scheduler:
    container_name: scheduler
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - mosquitto

  supply:
    container_name: supply
    build:
      context: ./supply
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9093:9093"
    depends_on:
      - mysql
      - flyway

  production:
    container_name: production
    build:
      context: ./production
      dockerfile: Dockerfile
    ports: 
      - "9091:9091"
    depends_on:
      - mosquitto

### Databases ####

  mysql:
    container_name: mysql
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: supply
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

### Middleware ####

  flyway:
    container_name: flyway
    image: flyway/flyway:latest
    command: -url=jdbc:mysql://mysql:3306/supply -user=root -password=password -connectRetries=60 -baselineOnMigrate=true migrate
    depends_on:
      - mysql
    volumes:
      - ./flyway-scripts:/flyway/sql
  
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  locust:
    build: ./locust
    container_name: locust
    command: locust -f mqtt_locustfile.py
    ports:
      - "8089:8089"
    links:
      - mosquitto

volumes:
  mysql_data:
  mongodb-data: