name: CI/CD Workflow

  # Workflow triggers
on:
  push:
    branches:
      - master

  # Environment Variables
env:
  DOCKER_IMAGE_SCHEDULER: scheduler
  DOCKER_IMAGE_SUPPLY: supply
  DOCKER_IMAGE_PRODUCTION: production
  GROUP_NUMBER: Group08 
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  # Create artifact of repository source code to use for consistensy accross all jobs
  clone-repository:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0
      - name: Upload Repository artifacts
        uses: actions/upload-artifact@v3
        with:
          name: repository-artifacts
          path: .
      - name: Upload Docker Compose
        uses: actions/upload-artifact@v3
        with:
          name: deployment-artifact
          path: |
            ./src/docker-compose.prod.yaml

  # Perform linting and/or other static code analysis
  code-analysis:
    runs-on: ubuntu-latest
    needs: clone-repository
    permissions:
      contents: read 
    # Allow continuation of pipeline if linting fails
    continue-on-error: true
    steps:
      - name: Download repository artifact
        uses: actions/download-artifact@v3
        with:
          name: repository-artifacts
          path: .
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y 
          echo "install your-linting-dependencies"
      - name: Run Linter / Other Code Analysis tool
        run: echo "running linter"
  
  # Job for compiling applicaitons and uploading as an artifact
  build-application:
    runs-on: ubuntu-latest
    needs: clone-repository
    steps:
      - name: Download repository artifact
        uses: actions/download-artifact@v3
        with:
          name: repository-artifacts
          path: .
      # Your logic for building the applicaiton, language dependent
      - name: Build application
        run:  echo "build app"
      # Upload compiled artifact
      - name: Upload Build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./src # Replace with path to your compiled artifact
  
  # Job for testing the application i.e 
  test-application:
    runs-on: ubuntu-latest
    needs: [build-application,code-analysis]
    # Allow pipeline to continue on error
    continue-on-error: true
    steps:
      # Download build artifact and use for applicaiton tests
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ./build
      - name: Test application
        run: echo "test"

  build-push-scheduler:
    runs-on: ubuntu-latest
    needs: [test-application]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Download repository artifact
        uses: actions/download-artifact@v3
        with:
          name: repository-artifacts
          path: .
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          # Authenticate with GitHub Container Registry, could be changed to use DockerHub
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Transform github.actor to lowercase
      - name: Transform username to lowercase
        run: echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      # Building and pushing application image go to: GitHub -> Profile -> Packages 
      - name: Build & Push image
        uses: docker/build-push-action@v3
        with:
          context: ./src/scheduler
          push: true
          tags: ghcr.io/${{ env.OWNER_LOWER }}/${{ env.DOCKER_IMAGE_SCHEDULER }}:1.0-${{ github.sha }},ghcr.io/${{ env.OWNER_LOWER }}/${{ env.DOCKER_IMAGE_SCHEDULER }}:latest

  build-push-supply:
    runs-on: ubuntu-latest
    needs: [test-application]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Download repository artifact
        uses: actions/download-artifact@v3
        with:
          name: repository-artifacts
          path: .
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file src/supply/pom.xml
      
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          # Authenticate with GitHub Container Registry, could be changed to use DockerHub
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Transform github.actor to lowercase
      - name: Transform username to lowercase
        run: echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      # Building and pushing application image go to: GitHub -> Profile -> Packages 
      - name: Build & Push image
        uses: docker/build-push-action@v3
        with:
          context: ./src/supply
          push: true
          tags: ghcr.io/${{ env.OWNER_LOWER }}/${{ env.DOCKER_IMAGE_SUPPLY }}:1.0-${{ github.sha }},ghcr.io/${{ env.OWNER_LOWER }}/${{ env.DOCKER_IMAGE_SUPPLY }}:latest

  build-push-production:
    runs-on: ubuntu-latest
    needs: [test-application]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Download repository artifact
        uses: actions/download-artifact@v3
        with:
          name: repository-artifacts
          path: .
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          # Authenticate with GitHub Container Registry, could be changed to use DockerHub
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Transform github.actor to lowercase
      - name: Transform username to lowercase
        run: echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      # Building and pushing application image go to: GitHub -> Profile -> Packages 
      - name: Build & Push image
        uses: docker/build-push-action@v3
        with:
          context: ./src/production
          push: true
          tags: ghcr.io/${{ env.OWNER_LOWER }}/${{ env.DOCKER_IMAGE_PRODUCTION }}:1.0-${{ github.sha }},ghcr.io/${{ env.OWNER_LOWER }}/${{ env.DOCKER_IMAGE_PRODUCTION }}:latest

  # Job for deploying the application, could be the logic for deploying to your VM  
  deploy-application:
    runs-on: self-hosted
    needs: [build-push-scheduler, build-push-supply, build-push-production]
    continue-on-error: true
    steps:
      - name: Download Deployment Artifact
        uses: actions/download-artifact@v3
        with:
          name: deployment-artifact
          path: ./src

      - name: Setup SSH Key
        run: |
          echo "${{ env.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          eval $(ssh-agent -s)
          ssh-add private_key.pem

      - name: Run command on VM
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ env.SSH_USERNAME }}@${{ env.SERVER_IP }} "echo Connection successful"

      - name: Transfer docker-compose to server
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem ./src/docker-compose.prod.yaml ${{ env.SSH_USERNAME }}@${{ env.SERVER_IP }}:./

      - name: Run Docker Login and Pull on VM
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ env.SSH_USERNAME }}@${{ env.SERVER_IP }} "echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin && docker pull ghcr.io/worldfam/scheduler:latest"

      - name: Run docker-compose Down on VM
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ env.SSH_USERNAME }}@${{ env.SERVER_IP }} "docker compose -f docker-compose.prod.yaml down"

      - name: Run docker-compose --build up on VM
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ env.SSH_USERNAME }}@${{ env.SERVER_IP }} "docker compose -f docker-compose.prod.yaml build --no-cache" &&
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ env.SSH_USERNAME }}@${{ env.SERVER_IP }} "docker compose -f docker-compose.prod.yaml up -d"